"""quotes

Revision ID: daily_quote_0001
Revises:
Create Date: 2026-09-27 17:19:31.711652
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "daily_quote_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_quote_quote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("picked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_quote_quote")
    # ### end Alembic commands ###
